/* Auto-generated by scripts/generate-firebase-config.js — do not edit manually */
/* To regenerate: set env vars and run: npm run build                           */
window.FIREBASE_CONFIG = {
  "enabled": true,
  "apiKey": "AIzaSyC2mOjX-F5eIy_MmQn_KxVUTPpU6uwNQng",
  "authDomain": "csrc-c32h.firebaseapp.com",
  "databaseURL": "https://csrc-c32h-default-rtdb.firebaseio.com",
  "projectId": "csrc-c32h",
  "storageBucket": "csrc-c32h.firebasestorage.app",
  "messagingSenderId": "280086200590",
  "appId": "1:280086200590:web:562d23389462f350f2575f"
};
