/* Auto-generated by scripts/generate-firebase-config.js — run: npm run build */
window.FIREBASE_CONFIG = {
  "enabled": false,
  "apiKey": "",
  "authDomain": "",
  "databaseURL": "",
  "projectId": "",
  "storageBucket": "",
  "messagingSenderId": "",
  "appId": ""
};
